// AUTO-GENERATED by vite-plugin-drizzle-zod-virtual. Do not edit.
import * as z from 'zod'
export { refineSchema } from '@omariyassine/drizzle-zod-plugin/refine'

export const insertSchema = z.object({
  "id": z.number().optional(),
  "status": z.enum(["active","pending","disabled"]).nullable().optional(),
  "config": z.union([z.union([z.string(), z.number(), z.boolean(), z.null()]), z.record(z.string(), z.any()), z.array(z.any())]).nullable().optional(),
  "createdAt": z.date().nullable().optional(),
  "activeYear": z.number().nullable().optional(),
  "binData": z.string().regex(/^[01]*$/).max(16).nullable().optional(),
  "blobData": z.string().max(65535).nullable().optional(),
  "flt": z.number().nullable().optional(),
  "dbl": z.number().nullable().optional(),
  "dec": z.string().nullable().optional(),
})
export const mysqlComplexTableInsertSchema = insertSchema

export const selectSchema = z.object({
  "id": z.number(),
  "status": z.enum(["active","pending","disabled"]).nullable(),
  "config": z.union([z.union([z.string(), z.number(), z.boolean(), z.null()]), z.record(z.string(), z.any()), z.array(z.any())]).nullable(),
  "createdAt": z.date().nullable(),
  "activeYear": z.number().nullable(),
  "binData": z.string().regex(/^[01]*$/).max(16).nullable(),
  "blobData": z.string().max(65535).nullable(),
  "flt": z.number().nullable(),
  "dbl": z.number().nullable(),
  "dec": z.string().nullable(),
})
export const mysqlComplexTableSelectSchema = selectSchema

export const updateSchema = z.object({
  "id": z.number().optional(),
  "status": z.enum(["active","pending","disabled"]).nullable().optional(),
  "config": z.union([z.union([z.string(), z.number(), z.boolean(), z.null()]), z.record(z.string(), z.any()), z.array(z.any())]).nullable().optional(),
  "createdAt": z.date().nullable().optional(),
  "activeYear": z.number().nullable().optional(),
  "binData": z.string().regex(/^[01]*$/).max(16).nullable().optional(),
  "blobData": z.string().max(65535).nullable().optional(),
  "flt": z.number().nullable().optional(),
  "dbl": z.number().nullable().optional(),
  "dec": z.string().nullable().optional(),
})
export const mysqlComplexTableUpdateSchema = updateSchema
