// AUTO-GENERATED by vite-plugin-drizzle-zod-virtual. Do not edit.
import * as z from 'zod'

export const insertSchema = z.object({
  "tenantId": z.uuid(),
  "userId": z.number(),
  "role": z.string().optional(),
})
export const pgCompositePkTableInsertSchema = insertSchema

export const selectSchema = z.object({
  "tenantId": z.uuid(),
  "userId": z.number(),
  "role": z.string(),
})
export const pgCompositePkTableSelectSchema = selectSchema

export const updateSchema = z.object({
  "tenantId": z.uuid().optional(),
  "userId": z.number().optional(),
  "role": z.string().optional(),
})
export const pgCompositePkTableUpdateSchema = updateSchema
