// AUTO-GENERATED by vite-plugin-drizzle-zod-virtual. Do not edit.
import * as z from 'zod'
export { refineSchema } from '@omariyassine/drizzle-zod-plugin/refine'

export const insertSchema = z.object({
  "id": z.number().optional(),
  "isFlag": z.boolean().nullable().optional(),
  "ts": z.date().nullable().optional(),
  "tsMs": z.date().nullable().optional(),
  "jsonField": z.union([z.union([z.string(), z.number(), z.boolean(), z.null()]), z.record(z.string(), z.any()), z.array(z.any())]).nullable().optional(),
  "enumField": z.enum(["low","medium","high"]).nullable().optional(),
  "blobBuf": z.custom().nullable().optional(),
  "blobJson": z.union([z.union([z.string(), z.number(), z.boolean(), z.null()]), z.record(z.string(), z.any()), z.array(z.any())]).nullable().optional(),
  "realVal": z.number().nullable().optional(),
  "numVal": z.string().nullable().optional(),
})
export const sqliteComplexTableInsertSchema = insertSchema

export const selectSchema = z.object({
  "id": z.number(),
  "isFlag": z.boolean().nullable(),
  "ts": z.date().nullable(),
  "tsMs": z.date().nullable(),
  "jsonField": z.union([z.union([z.string(), z.number(), z.boolean(), z.null()]), z.record(z.string(), z.any()), z.array(z.any())]).nullable(),
  "enumField": z.enum(["low","medium","high"]).nullable(),
  "blobBuf": z.custom().nullable(),
  "blobJson": z.union([z.union([z.string(), z.number(), z.boolean(), z.null()]), z.record(z.string(), z.any()), z.array(z.any())]).nullable(),
  "realVal": z.number().nullable(),
  "numVal": z.string().nullable(),
})
export const sqliteComplexTableSelectSchema = selectSchema

export const updateSchema = z.object({
  "id": z.number().optional(),
  "isFlag": z.boolean().nullable().optional(),
  "ts": z.date().nullable().optional(),
  "tsMs": z.date().nullable().optional(),
  "jsonField": z.union([z.union([z.string(), z.number(), z.boolean(), z.null()]), z.record(z.string(), z.any()), z.array(z.any())]).nullable().optional(),
  "enumField": z.enum(["low","medium","high"]).nullable().optional(),
  "blobBuf": z.custom().nullable().optional(),
  "blobJson": z.union([z.union([z.string(), z.number(), z.boolean(), z.null()]), z.record(z.string(), z.any()), z.array(z.any())]).nullable().optional(),
  "realVal": z.number().nullable().optional(),
  "numVal": z.string().nullable().optional(),
})
export const sqliteComplexTableUpdateSchema = updateSchema
