import { dirname, join as joinPath, relative } from "node:path";
import type { GeneratedData } from "./types";

export function buildDts(opts: {
	dtsLocation: string;
	outputPath: string;
	outputDir: string;
	moduleId: string;
	splitByTable: boolean;
	data: Pick<GeneratedData, "exportNames" | "tableCodes">;
}): string {
	const { dtsLocation, outputPath, outputDir, moduleId, splitByTable, data } =
		opts;

	let relImport = relative(dirname(dtsLocation), outputPath)
		.replace(/\\/g, "/")
		.replace(/\.ts$/, "");
	if (!relImport.startsWith(".")) relImport = `./${relImport}`;

	const rootExportLines = [
		`export const refineSchema: (typeof import('@omariyassine/drizzle-zod-plugin/refine'))['refineSchema']`,
		...data.exportNames.map(
			(name) =>
				`export const ${name}: (typeof import('${relImport}'))['${name}']`,
		),
	].join("\n  ");

	const subModuleDeclarations: string[] = [];
	for (const tableName of data.tableCodes.keys()) {
		const insertName = `${tableName}InsertSchema`;
		const selectName = `${tableName}SelectSchema`;
		const updateName = `${tableName}UpdateSchema`;

		const subRelImport = splitByTable
			? (() => {
					let p = relative(
						dirname(dtsLocation),
						joinPath(outputDir, `${tableName}.ts`),
					)
						.replace(/\\/g, "/")
						.replace(/\.ts$/, "");
					if (!p.startsWith(".")) p = `./${p}`;
					return p;
				})()
			: relImport;

		const aliasLines = [
			`export const refineSchema: (typeof import('@omariyassine/drizzle-zod-plugin/refine'))['refineSchema']`,
			`export const insertSchema: (typeof import('${subRelImport}'))['${splitByTable ? "insertSchema" : insertName}']`,
			`export const selectSchema: (typeof import('${subRelImport}'))['${splitByTable ? "selectSchema" : selectName}']`,
			`export const updateSchema: (typeof import('${subRelImport}'))['${splitByTable ? "updateSchema" : updateName}']`,
		].join("\n  ");

		subModuleDeclarations.push(
			`declare module '${moduleId}/${tableName}' {\n  ${aliasLines}\n}`,
		);
	}

	return (
		`// AUTO-GENERATED by vite-plugin-drizzle-zod-virtual. Do not edit.\n` +
		`// Gives '${moduleId}' real, fully-inferred TypeScript types via the\n` +
		`// "(typeof import('...'))['x']" type-query form.\n` +
		`declare module '${moduleId}' {\n` +
		`  ${rootExportLines}\n` +
		`}\n\n` +
		subModuleDeclarations.join("\n\n") +
		"\n"
	);
}
