import { mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join as joinPath, resolve as resolvePath } from "node:path";
import { buildDts } from "./dts-builder";

import type {
	DrizzleZodVirtualOptions,
	GeneratedData,
	ResolvedPaths,
} from "./types";

export async function writeGeneratedFiles(opts: {
	paths: ResolvedPaths;
	options: DrizzleZodVirtualOptions;
	viteRoot: string;
	splitByTable: boolean;
	moduleId: string;
	data: GeneratedData;
}): Promise<void> {
	const { paths, options, viteRoot, splitByTable, moduleId, data } = opts;
	const { absoluteOutputPath, absoluteOutputDir, dtsPath } = paths;

	const nodeTypesDir = joinPath(
		viteRoot,
		"node_modules",
		"@types",
		"virtual-drizzle-zod",
	);

	const fileWritePromises: Promise<void>[] = [];

	if (splitByTable) {
		// Ensure output directory exists
		await mkdir(absoluteOutputDir, { recursive: true });

		// Write individual per-table files
		for (const [tableName, tableData] of data.tableCodes.entries()) {
			const [insertCode, selectCode, updateCode] = tableData.zodCodes;
			const [insertName, selectName, updateName] = tableData.exportNames;

			const perTableCode = [
				"// AUTO-GENERATED by vite-plugin-drizzle-zod-virtual. Do not edit.",
				"import * as z from 'zod'",
				"",
				`export const insertSchema = ${insertCode}`,
				`export const ${insertName} = insertSchema`,
				"",
				`export const selectSchema = ${selectCode}`,
				`export const ${selectName} = selectSchema`,
				"",
				`export const updateSchema = ${updateCode}`,
				`export const ${updateName} = updateSchema`,
				"",
			].join("\n");

			const tableFilePath = joinPath(absoluteOutputDir, `${tableName}.ts`);
			fileWritePromises.push(writeFile(tableFilePath, perTableCode));
		}

		// Write barrel index.ts
		const barrelLines = [
			"// AUTO-GENERATED by vite-plugin-drizzle-zod-virtual. Do not edit.",
			"",
			...Array.from(data.tableCodes.keys()).map(
				(tableName) => `export * from './${tableName}'`,
			),
			"",
		];
		fileWritePromises.push(
			writeFile(absoluteOutputPath, barrelLines.join("\n")),
		);
	} else {
		// Single-file mode: write everything to one file
		fileWritePromises.push(
			mkdir(dirname(absoluteOutputPath), { recursive: true }).then(() =>
				writeFile(absoluteOutputPath, data.singleFileCode),
			),
		);
	}

	// Build .d.ts with correct relative paths for each output location
	const primaryDts = buildDts({
		dtsLocation: dtsPath,
		outputPath: absoluteOutputPath,
		outputDir: absoluteOutputDir,
		moduleId,
		splitByTable,
		data,
	});
	const nodeTypesDtsPath = joinPath(nodeTypesDir, "index.d.ts");
	const nodeTypesDts = buildDts({
		dtsLocation: nodeTypesDtsPath,
		outputPath: absoluteOutputPath,
		outputDir: absoluteOutputDir,
		moduleId,
		splitByTable,
		data,
	});

	// Write primary .d.ts
	fileWritePromises.push(
		mkdir(dirname(dtsPath), { recursive: true }).then(() =>
			writeFile(dtsPath, primaryDts),
		),
	);
	// Write @types shim with its own correctly computed relative paths
	fileWritePromises.push(
		mkdir(nodeTypesDir, { recursive: true })
			.then(() => writeFile(nodeTypesDtsPath, nodeTypesDts))
			.catch(() => {}),
	);

	// Clean up old internal output directory when user specifies a custom
	// outputPath, so stale files don't confuse TypeScript type resolution.
	if (typeof options.outputPath === "string") {
		const internalDir = resolvePath(
			viteRoot,
			"node_modules",
			".drizzle-zod-plugin",
		);
		fileWritePromises.push(
			rm(internalDir, { recursive: true, force: true }).catch(() => {}),
		);
	}

	await Promise.all(fileWritePromises);

	const isInternal = typeof options.outputPath !== "string";
	if (isInternal) {
		console.log(
			`[drizzle-zod-virtual] schemas generated (internal mode, omitting outputPath keeps files hidden)`,
		);
	} else if (splitByTable) {
		const tableCount = data.tableCodes.size;
		console.log(
			`[drizzle-zod-virtual] wrote ${tableCount} table files + index.ts to ${absoluteOutputDir} (root: ${viteRoot})`,
		);
	} else {
		console.log(
			`[drizzle-zod-virtual] wrote ${absoluteOutputPath} + ${dtsPath} (root: ${viteRoot})`,
		);
	}
}
