import { mkdir, rm, writeFile } from "node:fs/promises";
import { join as joinPath, resolve as resolvePath } from "node:path";
import { pathToFileURL } from "node:url";
import * as esbuild from "esbuild";
import type { GeneratedData, TableCodeData } from "./types";
import { zodTypeToCode } from "./zod-serializer";

export async function generateSchemas(opts: {
	absoluteSchemaPath: string;
	schemaPath: string;
	tmpDir: string;
	viteRoot: string;
	tables?: string[];
	moduleId?: string;
}): Promise<GeneratedData> {
	const { absoluteSchemaPath, schemaPath, tmpDir, viteRoot, tables } = opts;
	const moduleId = opts.moduleId ?? "virtual:drizzle-zod";

	const { createInsertSchema, createSelectSchema, createUpdateSchema } =
		await import("drizzle-orm/zod");

	const { is, Table } = await import("drizzle-orm");

	const result = await esbuild.build({
		entryPoints: [absoluteSchemaPath],
		absWorkingDir: viteRoot,
		bundle: true,
		platform: "node",
		format: "esm",
		packages: "external",
		write: false,
		metafile: true,
		logLevel: "silent",
	});

	const bundledCode = result.outputFiles?.[0]?.text;
	if (!bundledCode) {
		throw new Error("[drizzle-zod-virtual] Failed to bundle schema file");
	}

	await mkdir(tmpDir, { recursive: true });
	const tmpFile = joinPath(tmpDir, `schema-${Date.now()}.mjs`);
	await writeFile(tmpFile, bundledCode);

	let schemaModule: Record<string, unknown>;
	try {
		schemaModule = await import(pathToFileURL(tmpFile).href);
	} finally {
		await rm(tmpFile, { force: true });
	}

	const barrelChunks: string[] = [
		"// AUTO-GENERATED by vite-plugin-drizzle-zod-virtual. Do not edit.",
		"export { refineSchema } from '@omariyassine/drizzle-zod-plugin/refine'",
		"",
	];

	const singleFileChunks: string[] = [
		"// AUTO-GENERATED by vite-plugin-drizzle-zod-virtual. Do not edit.",
		"import * as z from 'zod'",
		"export { refineSchema } from '@omariyassine/drizzle-zod-plugin/refine'",
		"",
	];

	const tableNames =
		tables ??
		Object.entries(schemaModule)
			.filter(([, value]) => is(value, Table))
			.map(([key]) => key);

	if (tableNames.length === 0) {
		throw new Error(
			`[drizzle-zod-virtual] No Drizzle tables found in ${absoluteSchemaPath}. ` +
				`Either export some pgTable(...) values from it, or pass an explicit "tables" option.`,
		);
	}

	const exportNames: string[] = [];
	const tableCodes = new Map<string, TableCodeData>();

	for (const tableName of tableNames) {
		const table = schemaModule[tableName] as any;
		if (!table) {
			throw new Error(
				`[drizzle-zod-virtual] Table "${tableName}" not exported from ${schemaPath}`,
			);
		}

		const insertSchema = createInsertSchema(table);
		const selectSchema = createSelectSchema(table);
		const updateSchema = createUpdateSchema(table);

		const names = [
			`${tableName}InsertSchema`,
			`${tableName}SelectSchema`,
			`${tableName}UpdateSchema`,
		];
		exportNames.push(...names);

		const insertCode = zodTypeToCode(insertSchema);
		const selectCode = zodTypeToCode(selectSchema);
		const updateCode = zodTypeToCode(updateSchema);

		barrelChunks.push(
			`export { insertSchema as ${names[0]}, selectSchema as ${names[1]}, updateSchema as ${names[2]} } from '${moduleId}/${tableName}'`,
		);

		singleFileChunks.push(
			`export const ${names[0]} = /* @__PURE__ */ ${insertCode}`,
		);
		singleFileChunks.push(
			`export const ${names[1]} = /* @__PURE__ */ ${selectCode}`,
		);
		singleFileChunks.push(
			`export const ${names[2]} = /* @__PURE__ */ ${updateCode}`,
		);
		singleFileChunks.push("");

		const subModuleChunks = [
			"// AUTO-GENERATED by vite-plugin-drizzle-zod-virtual. Do not edit.",
			"import * as z from 'zod'",
			"export { refineSchema } from '@omariyassine/drizzle-zod-plugin/refine'",
			"",
			`export const insertSchema = /* @__PURE__ */ ${insertCode}`,
			`export const selectSchema = /* @__PURE__ */ ${selectCode}`,
			`export const updateSchema = /* @__PURE__ */ ${updateCode}`,
		];

		tableCodes.set(tableName, {
			code: subModuleChunks.join("\n"),
			exportNames: names,
			zodCodes: [insertCode, selectCode, updateCode],
		});
	}

	const depPaths: string[] = [];
	for (const [p] of Object.entries(result.metafile?.inputs ?? {})) {
		if (!p.includes("node_modules")) {
			depPaths.push(resolvePath(viteRoot, p));
		}
	}

	return {
		code: barrelChunks.join("\n"),
		singleFileCode: singleFileChunks.join("\n"),
		exportNames,
		tableCodes,
		depPaths,
	};
}
